# Generated by Django 5.1.4 on 2024-12-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOfUser',
            fields=[
                ('ID_account', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Body_measures', models.TextField(blank=True, null=True)),
                ('Preferences_list', models.TextField(blank=True, null=True)),
                ('User_s_autoproducts', models.TextField(blank=True, null=True)),
                ('User_s_sets', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autoproduct',
            fields=[
                ('ID_autoproduct', models.AutoField(primary_key=True, serialize=False)),
                ('Autoproduct_photo', models.ImageField(blank=True, null=True, upload_to='autoproduct_photos/')),
                ('Autoproduct_type', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('In_stock_size', models.CharField(max_length=20)),
                ('Material', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=20)),
                ('Weight', models.CharField(max_length=20)),
                ('Size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfFeatures',
            fields=[
                ('ID_list', models.AutoField(primary_key=True, serialize=False)),
                ('Amount_of_in_stock', models.CharField(max_length=20)),
                ('Brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SetOfItems',
            fields=[
                ('ID_set', models.AutoField(primary_key=True, serialize=False)),
                ('Name_of_set', models.CharField(max_length=50)),
                ('Creation_date', models.DateTimeField()),
                ('Set_style', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('ID_store', models.AutoField(primary_key=True, serialize=False)),
                ('Store_name', models.CharField(max_length=100)),
                ('URL', models.URLField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogAutoproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine_autoproducts.accountofuser')),
                ('ID_autoproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine_autoproducts.autoproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ListOfErrors',
            fields=[
                ('ID_Log', models.AutoField(primary_key=True, serialize=False)),
                ('Log_name', models.CharField(max_length=100)),
                ('Date_of_request', models.DateTimeField()),
                ('Description_of_error', models.TextField()),
                ('ID_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine_autoproducts.accountofuser')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine_autoproducts.accountofuser')),
                ('ID_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine_autoproducts.setofitems')),
            ],
        ),
        migrations.AddField(
            model_name='autoproduct',
            name='ID_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine_autoproducts.store'),
        ),
    ]
